CREATE TABLE tab_pessoas (
	ID		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOME	VARCHAR(200) NOT NULL
)
GO

CREATE TABLE tab_contatos (
	ID			INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_PESSOA	INT NOT NULL FOREIGN KEY REFERENCES tab_pessoas(ID),
	NOME		VARCHAR(200) NOT NULL
)
GO

CREATE TABLE tab_telefones (
	ID			INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_CONTATO	INT NOT NULL FOREIGN KEY REFERENCES tab_contatos(ID),
	PAIS		INT NOT NULL DEFAULT(55),
	DDD			INT NOT NULL,
	NUMERO		INT NOT NULL,
	WHATSAPP	BIT NOT NULL DEFAULT(0),
	OBSERVACAO	VARCHAR(MAX) NULL
)
GO

CREATE TABLE tab_emails (
	ID			INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_CONTATO	INT NOT NULL FOREIGN KEY REFERENCES tab_contatos(ID),
	EMAIL		VARCHAR(300) NOT NULL
)
GO
